//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronRestarter) DeepCopyInto(out *CronRestarter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronRestarter.
func (in *CronRestarter) DeepCopy() *CronRestarter {
	if in == nil {
		return nil
	}
	out := new(CronRestarter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronRestarter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronRestarterList) DeepCopyInto(out *CronRestarterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronRestarter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronRestarterList.
func (in *CronRestarterList) DeepCopy() *CronRestarterList {
	if in == nil {
		return nil
	}
	out := new(CronRestarterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronRestarterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronRestarterSpec) DeepCopyInto(out *CronRestarterSpec) {
	*out = *in
	if in.ExcludeDates != nil {
		in, out := &in.ExcludeDates, &out.ExcludeDates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.RestartTargetRef = in.RestartTargetRef
	if in.MisfireDeadWindowMinutes != nil {
		in, out := &in.MisfireDeadWindowMinutes, &out.MisfireDeadWindowMinutes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronRestarterSpec.
func (in *CronRestarterSpec) DeepCopy() *CronRestarterSpec {
	if in == nil {
		return nil
	}
	out := new(CronRestarterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronRestarterStatus) DeepCopyInto(out *CronRestarterStatus) {
	*out = *in
	in.ProcessingTick.DeepCopyInto(&out.ProcessingTick)
	in.LastTickTimestamp.DeepCopyInto(&out.LastTickTimestamp)
	in.LastExecutionTime.DeepCopyInto(&out.LastExecutionTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronRestarterStatus.
func (in *CronRestarterStatus) DeepCopy() *CronRestarterStatus {
	if in == nil {
		return nil
	}
	out := new(CronRestarterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartTargetRef) DeepCopyInto(out *RestartTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartTargetRef.
func (in *RestartTargetRef) DeepCopy() *RestartTargetRef {
	if in == nil {
		return nil
	}
	out := new(RestartTargetRef)
	in.DeepCopyInto(out)
	return out
}
